export const TOGGLE_FILTER = 'TOGGLE_FILTER'
export const SEARCH_TASK = 'SEARCH_TASK'
export const CLEAR_SEARCH = 'CLEAR_SEARCH'
export const ADD_TASK = 'ADD_TASK'
export const REMOVE_TASK = 'REMOVE_TASK'
export const UPDATE_TASK = 'UPDATE_TASK'
export const EDIT_TASK = 'EDIT_TASK'
export const CLEAR_EDIT = 'CLEAR_EDIT'
export const GET_TASKS = 'GET_TASKS'
export const TASKS_ERROR = 'TASKS_ERROR'
export const ALL_GUESTS = 'ALL_GUESTS'


export const SUCCESS_REGISTER = 'SUCCESS_REGISTER'
export const FAIL_REGISTER = 'FAIL_REGISTER'
export const SUCCESS_LOGIN = 'SUCCESS_LOGIN'
export const FAIL_LOGIN = 'FAIL_LOGIN'
export const SET_ERROR = 'SET_ERROR'
export const CLEAR_ERROR = 'CLEAR_ERROR'
export const LOG_OUT = 'LOG_OUT'
export const SET_USER = 'SET_USER'
export const AUTH_ERROR = 'AUTH_ERROR'
